export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

// We're going to create the constants to handle the 3 states of our promise
// THIS IS PRETTY MUCH STANDARD WITH ALL AJAX ASYNCHRONOUS CALLS
export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAIL = 'REQUEST_ROBOTS_FAIL';
